### ISSUE TITLE
Social media links don’t have an accessible name

### ISSUE THREAD

**Issue by ZoeBijl** [nikkilr88/nikkilr88.github.io#11]
In #10 I mentioned accessible names:

>  The `span` with the `visually-hidden` class provides the link with an accessible name—which is used by assistive technologies.

Without an accessible name these links are announced simply as “link”. That doesn’t really tell us much about what they do. We can tell they’ll take us somewhere but not where.

https://github.com/nikkilr88/nikkilr88.github.io/blob/8d5d1790fe9081f411b99bd9322c932acfc722e7/index.html#L318-L332

The links can be given an accessible name with the same method as used in #10:

```HTML
<a href="https://twitter.com/nikkilr88" target="_blank">
  <i class="fab fa-twitter footer__icon" aria-hidden="true"></i>
  <span class="visually-hidden">Twitter</span>
</a>
```

Instead of invisible labels you could also provide visible labels for people that don’t recognise the icons.

**Comment by nikkilr88** [comment]
Thank you!

Could something like this work or is the hidden tag better?

` <a
          rel="noopener"
          target="_blank"
          href="https://codepen.io/nikkilr88/"
          aria-label="Go to DevNikki's Codepen"
        >
          <i class="fab fa-codepen footer__icon"></i>
        </a>`
